spring:
  profiles:
    active: dev

  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    password: 1234

---

spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.webtoon: debug

---

spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.webtoon: info